"""add fields

Revision ID: 784d69486569
Revises: 6ef4afc31814
Create Date: 2023-08-13 08:26:59.563496

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '784d69486569'
down_revision = '6ef4afc31814'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('user_history', sa.Column('showed', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user_history', sa.Column('opened', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user_history', sa.Column('liked', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('user_history', sa.Column('favourited', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'favourited')
    op.drop_column('user_history', 'liked')
    op.drop_column('user_history', 'opened')
    op.drop_column('user_history', 'showed')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
