"""org redactions

Revision ID: 9644c40c26cb
Revises: efc3d95de96f
Create Date: 2023-08-12 20:50:04.805157

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9644c40c26cb'
down_revision = 'efc3d95de96f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_events',
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], )
    )
    # op.drop_table('spatial_ref_sys')
    op.drop_column('org_to_users', 'id')
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['owner'], ['id'])
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'owner')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'email')
    op.add_column('org_to_users', sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_table('org_events')
    # ### end Alembic commands ###
